[bastion_node]
bastion ansible_host=44.193.30.92

[app_nodes]
app_server ansible_host=10.0.2.124

[jenkins_nodes]
jenkins_server ansible_host=10.0.2.144

[sonarqube_nodes]
sonarqube_server ansible_host=10.0.2.192

[observability_nodes]
observability_server ansible_host=10.0.2.7

[bastion_node:vars]
ansible_ssh_common_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

[app_nodes:vars]
ansible_ssh_common_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand='ssh -W %h:%p -q -i ~/.ssh/cloud_devops_keypair_26.pem ubuntu@44.193.30.92 -o StrictHostKeyChecking=no'"

[jenkins_nodes:vars]
ansible_ssh_common_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand='ssh -W %h:%p -q -i ~/.ssh/cloud_devops_keypair_26.pem ubuntu@44.193.30.92 -o StrictHostKeyChecking=no'"

[sonarqube_nodes:vars]
ansible_ssh_common_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand='ssh -W %h:%p -q -i ~/.ssh/cloud_devops_keypair_26.pem ubuntu@44.193.30.92 -o StrictHostKeyChecking=no'"

[observability_nodes:vars]
ansible_ssh_common_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand='ssh -W %h:%p -q -i ~/.ssh/cloud_devops_keypair_26.pem ubuntu@75.101.173.185 -o StrictHostKeyChecking=no'"

[all:vars]
ansible_ssh_private_key_file=~/.ssh/cloud_devops_keypair_26.pem
ansible_python_interpreter=/usr/bin/python3
