[bastion_node]
bastion ansible_host=44.222.143.249

[app_nodes]
app_server ansible_host=10.0.2.59

[bastion_node:vars]
ansible_ssh_common_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

[app_nodes:vars]
ansible_ssh_common_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand='ssh -W %h:%p -q -i /home/hawkhanan/.ssh/cloud_devops_keypair_26.pem ubuntu@44.222.143.249 -o StrictHostKeyChecking=no'"

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/hawkhanan/.ssh/cloud_devops_keypair_26.pem
ansible_python_interpreter=/usr/bin/python3