[bastion_node]
bastion ansible_host=100.48.205.89

[app_nodes]
app_server ansible_host=10.0.2.188

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/hawkhanan/.ssh/cloud_devops_keypair_26.pem
ansible_python_interpreter=/usr/bin/python3